#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: erp_php
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - mysql
    networks:
      - erp_network

  nginx:
    image: nginx:alpine
    container_name: erp_nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - erp_network

  mysql:
    image: mysql:8.0
    container_name: erp_mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - erp_network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: erp_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - erp_network

volumes:
  mysql_data:

networks:
  erp_network:
    driver: bridge